create or replace TYPE T_OBJECT_BKI IS OBJECT
("RR_CREDS_PK" NUMBER,
	"RESPONSE_ID" NUMBER,
  CRED_ID NUMBER, 
  CRED_DATE DATE, 
  CRED_ENDDATE DATE, 
  CRED_SUM_DEBT NUMBER, 
  CRED_ACTIVE NUMBER, 
  ADD_831 VARCHAR2(4000)
  );
  
  
  
create or replace TYPE T_TABLE_BKI IS TABLE OF T_OBJECT_BKI;