create or replace TYPE T_OBJECT_BKI IS OBJECT
("RR_CREDS_PK" NUMBER,
	"RESPONSE_ID" NUMBER,
  CRED_ID NUMBER, 
  CRED_SUM	NUMBER,
  CRED_CURRENCY	VARCHAR2(3 BYTE),
  CRED_DATE DATE, 
  CRED_ENDDATE DATE, 
  CRED_SUM_DEBT NUMBER, 
  CRED_TYPE	NUMBER,
  CRED_ACTIVE	NUMBER,
  ADD_831 VARCHAR2(4000),
  ANN_STR VARCHAR2(8000),
  ANN NUMBER
  );