CREATE OR REPLACE FUNCTION SFF.FN_STRIP_DUBL_IN_STR(inSTR IN VARCHAR2) 
  RETURN VARCHAR2
IS
	returnStr VARCHAR2(4000);
  
  /*CURSOR c1 RETURN tbl1%ROWTYPE IS 
    SELECT * FROM tbl1 WHERE f3 > 700;*/
BEGIN
  
  --SELECT REQUEST_ID_REL INTO returnStr FROM SFF.FROD_RULE WHERE REQUEST_ID=46523694;
	SELECT DISTINCT LISTAGG(REQUEST_ID_REL,',') WITHIN GROUP (ORDER BY REQUEST_ID) OVER(PARTITION BY REQUEST_ID) INTO returnStr
  FROM (select DISTINCT 1 as REQUEST_ID, regexp_substr(inSTR, '[^,]+', 1, level) REQUEST_ID_REL from dual t
          CONNECT BY instr(trim(',' from inSTR), ',' , 1, level - 1) > 0 
          ORDER BY REQUEST_ID_REL);
	
  --DBMS_OUTPUT.put_line('returning str: '||returnStr);
  RETURN returnStr;
END;
/
