create or replace FUNCTION "FN$BKI_CALC_ANNUITY"(TBL_BKI_read IN T_OBJECT_BKI) RETURN NUMBER
IS
  CRED_PERSENT NUMBER  := 0.30;
  
  P NUMBER;
  N NUMBER;
  CRED_ANNUITY NUMBER(12,0);
BEGIN
  DBMS_OUTPUT.enable;
    
  P := (CRED_PERSENT/12);
  N := ROUND(MONTHS_BETWEEN(TBL_BKI_read.CRED_ENDDATE, TBL_BKI_read.CRED_DATE));
  
  --DBMS_OUTPUT.put_line((N));
  CRED_ANNUITY := TBL_BKI_read.CRED_SUM * (P + (P/(POWER(1+P, N)-1) ) );
  
  --DBMS_OUTPUT.put_line((str_join));
  RETURN (CRED_ANNUITY);
END;